version: 0.1

phases:
  pre_build:
    commands:
      - echo Starting build...
  build:
    commands:
      - echo Building the AMI using Packer...          
      - packer build -machine-readable packer.json
  post_build:
    commands:
      - echo Build completed on `date`
