version: 0.1

phases:
  pre_build:
    commands:
      - echo Starting build...
      - echo Access Key is `echo $AWS_ACCESS_KEY`
      - echo Secret Key is `echo $AWS_SECRET_KEY`
      - echo Listing S3 buckets...
      - aws s3api list-buckets --query 'Buckets[].Name'
  build:
    commands:
      - echo Building the AMI using Packer...          
      - packer build -machine-readable packer.json
  post_build:
    commands:
      - echo Build completed on `date`
